// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArticle(ctx context.Context, id pgtype.UUID) error
	GetArticleByID(ctx context.Context, id pgtype.UUID) (Article, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	ListArticlesByAuthor(ctx context.Context, arg ListArticlesByAuthorParams) ([]Article, error)
	ListPermissionsByRoleID(ctx context.Context, roleID int32) ([]string, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
}

var _ Querier = (*Queries)(nil)
