// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlc

import (
	"context"
)

const listPermissionsByRoleID = `-- name: ListPermissionsByRoleID :many
SELECT
  p.name
FROM permissions p
  INNER JOIN role_permissions rp ON rp.permission_id = p.id
WHERE
  rp.role_id = $1
ORDER BY
  p.name
`

func (q *Queries) ListPermissionsByRoleID(ctx context.Context, roleID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
